version: 2
updates:
  # Smart Contracts
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    reviewers:
      - "borneotrace-security-team"
    assignees:
      - "smart-contract-developer"
    commit-message:
      prefix: "contracts"
      include: "scope"
    labels:
      - "dependencies"
      - "smart-contracts"
    groups:
      hardhat:
        patterns:
          - "@nomicfoundation/hardhat-*"
          - "hardhat*"
      openzeppelin:
        patterns:
          - "@openzeppelin/contracts*"
      testing:
        patterns:
          - "@typechain/*"
          - "typechain*"
          - "solidity-coverage"
          - "hardhat-gas-reporter"

  # Frontend Application
  - package-ecosystem: "npm"
    directory: "/borneo-trace-app"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    reviewers:
      - "borneotrace-frontend-team"
    assignees:
      - "frontend-developer"
    commit-message:
      prefix: "frontend"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      web3:
        patterns:
          - "ethers"
          - "web3"
          - "@metamask/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "playwright*"

  # Backend API
  - package-ecosystem: "npm"
    directory: "/backend-api"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    reviewers:
      - "borneotrace-backend-team"
    assignees:
      - "backend-developer"
    commit-message:
      prefix: "backend"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    groups:
      express:
        patterns:
          - "express*"
          - "@types/express*"
      database:
        patterns:
          - "pg*"
          - "prisma*"
          - "mongoose*"
      security:
        patterns:
          - "helmet"
          - "cors"
          - "bcrypt*"
          - "jsonwebtoken"

  # Mobile Application
  - package-ecosystem: "npm"
    directory: "/mobile-app"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 10
    reviewers:
      - "borneotrace-mobile-team"
    assignees:
      - "mobile-developer"
    commit-message:
      prefix: "mobile"
      include: "scope"
    labels:
      - "dependencies"
      - "mobile"
    groups:
      react-native:
        patterns:
          - "react-native*"
          - "@react-native/*"
      navigation:
        patterns:
          - "@react-navigation/*"
      testing:
        patterns:
          - "detox*"
          - "@testing-library/react-native"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Kuala_Lumpur"
    open-pull-requests-limit: 5
    reviewers:
      - "borneotrace-devops-team"
    assignees:
      - "devops-engineer"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "actions/*"
      node-setup:
        patterns:
          - "actions/setup-node*"
      aws:
        patterns:
          - "aws-actions/*"
      docker:
        patterns:
          - "docker/*"
