name: ✨ Feature Request
description: Suggest a new feature or enhancement for BorneoTrace
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below with as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Smart Contracts
        - Frontend Web App
        - Backend API
        - Mobile App
        - Documentation
        - CI/CD Pipeline
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for core functionality
        - Critical - Blocking issue
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe how you think this should work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions you've considered?
      placeholder: Describe any alternatives you've considered...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Who would use this feature and how?
      placeholder: Describe the use cases and user stories...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort do you think this would take?
      options:
        - Small - A few hours
        - Medium - A few days
        - Large - A few weeks
        - Extra Large - A few months
        - Unknown

  - type: checkboxes
    id: checklist
    attributes:
      label: Feature Request Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: I have considered the impact on existing functionality
          required: true
